[package]
name = "pitched"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.1"
pareg = "0.10.0"
rand = "0.9.1"
termal = { version = "3.0.1", features = ["readers"] }
thiserror = "2.0.12"
